title: "Schrodinger"
description: "An Arrow Option implementation with Kotlin Nullable type"s
url: https://kioba.dev/schrodinger
relative_permalinks: false

markdown: kramdown
theme: jekyll-theme-slate